name: Python Package Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']
        include:
          - python-version: '3.10'
            python-dev-package: 'python3.10-dev'
          - python-version: '3.11'
            python-dev-package: 'python3.11-dev'
          - python-version: '3.12'
            python-dev-package: 'python3.12-dev'
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y portaudio19-dev ffmpeg ${{ matrix.python-dev-package }}
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
    - name: Test installation
      run: |
        which speechcatcher
        speechcatcher --help
        speechcatcher https://upload.wikimedia.org/wikipedia/commons/6/65/LibriVox_-_Fontane_Herr_von_Ribbeck.ogg
